mine-regent: #in seconds
  stone: 3
  cobblestone: 3
  iron_ore: 5
  gold_ore: 5
  diamond_ore: 8
  lapis_ore: 6
  emerald_ore: 8
  redstone_ore: 6
  coal_ore: 4

no-permissions: "&7[&aChyba&7] Na toto nemáš dostatočnú hodnosť :D"

permissions:
  double-drop: "gl.vip"
  gamemode: "gl.gm"
  gamemode-other: "gl.gm.other"

auth:
  database:
    ip: "mysql.hostify.cz"
    databse: ""
    username: ""
    password: ""
    port: 3306
